version: '3.8'

services:
  # Сервис нашей базы данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: recording_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recording_db
    ports:
      - "5433:5432" # Пробрасываем на 5433, чтобы не конфликтовать с твоим локальным pgAdmin (5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сервис нашего FastAPI бэкенда
  web:
    build: .
    container_name: fastapi_app_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/recording_db
    depends_on:
      - db

volumes:
  postgres_data: